stages:
  - lint
  - test
  - mirror

.composer-install:
  before_script:
    - mkdir -p .composer/cache
    - COMPOSER_CACHE_DIR=.composer/cache composer install
  cache:
    key: composer-cache
    paths:
      - .composer/cache

.install-typo3:
  before_script:
    - mkdir -p .composer/cache
    - |
      COMPOSER_CACHE_DIR=.composer/cache composer require \
        typo3/cms-backend="$TYPO3_VERSION" \
        typo3/cms-recordlist="$TYPO3_VERSION" \
        typo3/cms-core="$TYPO3_VERSION" \
        typo3/cms-extbase="$TYPO3_VERSION" \
        typo3/cms-extensionmanager="$TYPO3_VERSION" \
        typo3/cms-fluid="$TYPO3_VERSION" \
        typo3/cms-frontend="$TYPO3_VERSION" \
        typo3/cms-install="$TYPO3_VERSION" \
        typo3/cms-recordlist="$TYPO3_VERSION"
    - echo '<?php return [];' > .Build/Web/typo3conf/LocalConfiguration.php

lint-php:
  stage: lint
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php$PHP_VERSION
  except:
    - master
  script:
    - find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  parallel:
    matrix:
      - PHP_VERSION: [ '7.4', '8.0' ]

codestyle-php:
  stage: lint
  except:
    - master
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php7.4
  before_script:
    - mkdir -p .composer/cache
    - COMPOSER_CACHE_DIR=.composer/cache composer install
  script:
    - composer phpcsfixer
  cache:
    key: composer-cache
    paths:
      - .composer/cache

php:phpstan:
  stage: lint
  except:
    - master
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php$PHP_VERSION
  before_script:
    - mkdir -p .composer/cache
    # Remove typo3-console because it is not needed here and currently not compatible with v12.
    - COMPOSER_CACHE_DIR=.composer/cache composer remove --dev --no-update helhum/typo3-console && rm -f composer.lock
    - COMPOSER_CACHE_DIR=.composer/cache composer require typo3/cms-core="$TYPO3_VERSION"
    - echo '<?php return [];' > .Build/Web/typo3conf/LocalConfiguration.php
  script:
    - composer phpstan
  cache:
    key: composer-cache
    paths:
      - .composer/cache
  parallel:
    matrix:
      - TYPO3_VERSION: '^11'
        PHP_VERSION: [ '7.4', '8.0' ]
      - TYPO3_VERSION: '^10'
        PHP_VERSION: [ '7.4' ]

unit-tests:
  extends:
    - .composer-install
    - .install-typo3
  stage: test
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php$PHP_VERSION
  except:
    - master
  script:
    - .Build/bin/phpunit --colors -c .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit/
  parallel:
    matrix:
      - TYPO3_VERSION: '^11.4'
        PHP_VERSION: [ '7.4', '8.0' ]
      - TYPO3_VERSION: '^10.4'
        PHP_VERSION: [ '7.4' ]

mirror:
  stage: mirror
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php7.4
  only:
    - main
    - tags
  variables:
    GIT_STRATEGY: none
  script:
    - git clone $CI_REPOSITORY_URL -b main repo && cd repo
    - git config user.name "$GIT_USER_NAME"
    - git config user.email "$GIT_USER_EMAIL"
    - git checkout master && git merge --ff main
    - git push https://$GITLAB_USERNAME:M2_$GITLAB_TOKEN@$GITLAB_REPOSITORY
    - git push -f --mirror https://$GITHUB_USERNAME:ghp_$GITHUB_TOKEN@$GITHUB_REPOSITORY
