services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Codemonkey1988\BeStaticAuth\:
    resource: '../Classes/*'

  Codemonkey1988\BeStaticAuth\Service\StaticAuthenticationService:
    public: true
